# Generated by Django 5.0.1 on 2024-02-28 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccm_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_datetime', models.DateTimeField(auto_now_add=True)),
                ('action_details', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('database_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccm_app.record')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
