# Generated by Django 5.0.3 on 2024-03-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccm_app', '0002_record_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='archived',
        ),
    ]
